const QUESTIONS = {
    hiragana: [
        ['あ', 'A'],
        ['い', 'I'],
        ['う', 'U'],
        ['え', 'E'],
        ['お', 'O'],
        ['か', 'KA'],
        ['き', 'KI'],
        ['く', 'KU'],
        ['け', 'KE'],
        ['こ', 'KO'],
        ['が', 'GA'],
        ['ぎ', 'GI'],
        ['ぐ', 'GU'],
        ['げ', 'GE'],
        ['ご', 'GO'],
        ['さ', 'SA'],
        ['し', 'SHI'],
        ['す', 'SU'],
        ['せ', 'SE'],
        ['そ', 'SO'],
        ['ざ', 'ZA'],
        ['じ', 'JI'],
        ['ず', 'ZU'],
        ['ぜ', 'ZE'],
        ['ぞ', 'ZO'],
        ['た', 'TA'],
        ['ち', 'CHI'],
        ['つ', 'TSU'],
        ['て', 'TE'],
        ['と', 'TO'],
        ['だ', 'DA'],
        ['ぢ', 'JI'],
        ['づ', 'ZU'],
        ['で', 'DE'],
        ['ど', 'DO'],
        ['な', 'NA'],
        ['に', 'NI'],
        ['ぬ', 'NU'],
        ['ね', 'NE'],
        ['の', 'NO'],
        ['は', 'HA'],
        ['ひ', 'HI'],
        ['ふ', 'FU'],
        ['へ', 'HE'],
        ['ほ', 'HO'],
        ['ば', 'BA'],
        ['び', 'BI'],
        ['ぶ', 'BU'],
        ['べ', 'BE'],
        ['ぼ', 'BO'],
        ['ぱ', 'PA'],
        ['ぴ', 'PI'],
        ['ぷ', 'PU'],
        ['ぺ', 'PE'],
        ['ぽ', 'PO'],
        ['ま', 'MA'],
        ['み', 'MI'],
        ['む', 'MU'],
        ['め', 'ME'],
        ['も', 'MO'],
        ['や', 'YA'],
        ['ゆ', 'YU'],
        ['よ', 'YO'],
        ['ら', 'RA'],
        ['り', 'RI'],
        ['る', 'RU'],
        ['れ', 'RE'],
        ['ろ', 'RO'],
        ['わ', 'WA'],
        ['を', 'WO'],
        ['ん', 'N']
    ],
    hiraganaDigraphs: [
        ['きゃ', 'KYA'],
        ['きゅ', 'KYU'],
        ['きょ', 'KYO'],
        ['ぎゃ', 'GYA'],
        ['ぎゅ', 'GYU'],
        ['ぎょ', 'GYO'],
        ['しゃ', 'SHA'],
        ['しゅ', 'SHU'],
        ['しょ', 'SHO'],
        ['じゃ', 'JA'],
        ['じゅ', 'JU'],
        ['じょ', 'JO'],
        ['ちゃ', 'CHA'],
        ['ちゅ', 'CHU'],
        ['ちょ', 'CHO'],
        ['にゃ', 'NYA'],
        ['にゅ', 'NYU'],
        ['にょ', 'NYO'],
        ['ひゃ', 'HYA'],
        ['ひゅ', 'HYU'],
        ['ひょ', 'HYO'],
        ['びゃ', 'BYA'],
        ['びゅ', 'BYU'],
        ['びょ', 'BYO'],
        ['ぴゃ', 'PYA'],
        ['ぴゅ', 'PYU'],
        ['ぴょ', 'PYO'],
        ['みゃ', 'MYA'],
        ['みゅ', 'MYU'],
        ['みょ', 'MYO'],
        ['りゃ', 'RYA'],
        ['りゅ', 'RYU'],
        ['りょ', 'RYO']
    ],
    katakana: [
        ['ア', 'A'],
        ['イ', 'I'],
        ['ウ', 'U'],
        ['エ', 'E'],
        ['オ', 'O'],
        ['カ', 'KA'],
        ['キ', 'KI'],
        ['ク', 'KU'],
        ['ケ', 'KE'],
        ['コ', 'KO'],
        ['サ', 'SA'],
        ['シ', 'SHI'],
        ['ス', 'SU'],
        ['セ', 'SE'],
        ['ソ', 'SO'],
        ['タ', 'TA'],
        ['チ', 'CHI'],
        ['ツ', 'TSU'],
        ['テ', 'TE'],
        ['ト', 'TO'],
        ['ナ', 'NA'],
        ['ニ', 'NI'],
        ['ヌ', 'NU'],
        ['ネ', 'NE'],
        ['ノ', 'NO'],
        ['ハ', 'HA'],
        ['ヒ', 'HI'],
        ['フ', 'FU'],
        ['ヘ', 'HE'],
        ['ホ', 'HO'],
        ['マ', 'MA'],
        ['ミ', 'MI'],
        ['ム', 'MU'],
        ['メ', 'ME'],
        ['モ', 'MO'],
        ['ヤ', 'YA'],
        ['ユ', 'YU'],
        ['ヨ', 'YO'],
        ['ラ', 'RA'],
        ['リ', 'RI'],
        ['ル', 'RU'],
        ['レ', 'RE'],
        ['ロ', 'RO'],
        ['ワ', 'WA'],
        ['ヲ', 'WO'],
        ['ン', 'N'],
        ['ガ', 'GA'],
        ['ギ', 'GI'],
        ['グ', 'GU'],
        ['ゲ', 'GE'],
        ['ゴ', 'GO'],
        ['ザ', 'ZA'],
        ['ジ', 'JI'],
        ['ズ', 'ZU'],
        ['ゼ', 'ZE'],
        ['ゾ', 'ZO'],
        ['ダ', 'DA'],
        ['ヂ', 'JI'],
        ['ヅ', 'ZU'],
        ['デ', 'DE'],
        ['ド', 'DO'],
        ['バ', 'BA'],
        ['ビ', 'BI'],
        ['ブ', 'BU'],
        ['ベ', 'BE'],
        ['ボ', 'BO'],
        ['パ', 'PA'],
        ['ピ', 'PI'],
        ['プ', 'PU'],
        ['ペ', 'PE'],
        ['ポ', 'PO']
    ],
    katakanaDigraphs: [
        ['キャ', 'KYA'],
        ['キュ', 'KYU'],
        ['キョ', 'KYO'],
        ['ギャ', 'GYA'],
        ['ギュ', 'GYU'],
        ['ギョ', 'GYO'],
        ['シャ', 'SHA'],
        ['シュ', 'SHU'],
        ['ショ', 'SHO'],
        ['ジャ', 'JA'],
        ['ジュ', 'JU'],
        ['ジョ', 'JO'],
        ['チャ', 'CHA'],
        ['チュ', 'CHU'],
        ['チョ', 'CHO'],
        ['ニャ', 'NYA'],
        ['ニュ', 'NYU'],
        ['ニョ', 'NYO'],
        ['ヒャ', 'HYA'],
        ['ヒュ', 'HYU'],
        ['ヒョ', 'HYO'],
        ['ビャ', 'BYA'],
        ['ビュ', 'BYU'],
        ['ビョ', 'BYO'],
        ['ピャ', 'PYA'],
        ['ピュ', 'PYU'],
        ['ピョ', 'PYO'],
        ['ミャ', 'MYA'],
        ['ミュ', 'MYU'],
        ['ミョ', 'MYO'],
        ['リャ', 'RYA'],
        ['リュ', 'RYU'],
        ['リョ', 'RYO']
    ],
    kanji: [
        // Kanji / Onyomi / Kunyomi / Meaning

        // Numbers
        ['一', 'いち', 'ひと－つ', 'one'],
        ['二', 'に', 'ふた－つ', 'two'],
        ['三', 'さん', 'みっ－つ', 'three'],
        ['四', 'し', 'よん / よっ－つ', 'four'],
        ['五', 'ご', 'いつ－つ', 'five'],
        ['六', 'ろく', 'むっ－つ / むい', 'six'],
        ['七', 'しち', 'なな－つ / なの / なぬ', 'seven'],
        ['八', 'はち', 'やっ－つ / よう', 'eight'],
        ['九', 'きゅう / く', 'ここの－つ', 'nine'],
        ['十', 'じゅう', 'とお / とう', 'ten'],
        ['百', 'ひゃく', 'もも', 'hundred'],
        ['千', 'せん', 'ち', 'thousand'],
        ['万', 'ばん / まん', 'よろず', 'ten thousand'],
        ['円', 'えん', 'まる－い / まど－か / つぶ－ら', 'circle / round / yen'],

        // Time
        ['日', 'じつ / にち', 'ひ / か', 'sun / day'],
        ['週', '', '', 'week'],
        ['月', 'がつ / げつ', 'つき', 'moon / month'],
        ['年', 'ねん', 'とし', 'year'],
        ['時', 'じ', 'とき', 'time / hour'],
        ['間', 'かん / けん', 'あいだ / ま', 'interval / span of time / time frame'],
        ['分', 'ぶん / ふん / ぶ', 'わ－ける / わ－かる / わ－かつ', 'minute / part / to divide / to understand'],
        ['午', 'ご', 'うま', 'noon'],
        ['前', 'ぜん', 'まえ / さき', 'before / in front of / previous'],
        ['後', 'ご / こう', 'うし－ろ / のち / あと', 'after / behind / later'],
        ['今', 'こん / きん', 'いま', 'now / the present'],
        ['先', 'せん', 'さき', 'previous / ahead / the future'],
        ['来', 'らい', 'く－る', 'to come'],
        ['半', 'はん', 'なか－ば', 'half / middle'],
        ['毎', 'まい', 'ごと', 'every / each'],
        ['何', 'か', 'なに / なん / いず－れ', 'what / which / how many'],

        // People and things
        ['人', 'じん / にん', 'ひと', 'person'],
        ['男', 'だん / なん', 'おとこ / おのこ / お', 'man / male'],
        ['女', 'じょ / にょ', 'おんな', 'woman / female'],
        ['子', 'し / す', 'こ / ね', 'child'],
        ['母', 'ぼ / も', 'はは', 'mother'],
        ['父', 'ふ', 'ちち', 'father'],
        ['友', 'ゆう', 'とも', 'friend'],
        ['火', 'か', 'ひ / ほ', 'fire / light'],
        ['水', 'すい', 'みず', 'water'],
        ['木', 'もく / ぼく', 'き', 'tree / wood'],
        ['土', 'ど / と', 'つち', 'earth / ground / soil'],
        ['金', 'きん / こん', 'かね', 'gold / money'],
        ['本', 'ほん', 'もと', 'root / source / book'],
        ['川', 'せん', 'かわ', 'river / stream'],
        ['花', '', '', 'flower'],
        ['気', 'き / け', '', 'spirit / intention / mind / power / energy'],
        ['生', 'せい / しょう', 'う－む / い－きる / なま', 'birth / life / to give birth / to live / raw'],
        ['魚', '', '', 'fish'],
        ['天', 'てん', 'あま / あめ', 'heaven / sky'],
        ['空', '', '', 'sky / empty'],
        ['山', 'さん / せん', 'やま', 'mountain'],
        ['雨', 'う', 'あま / あめ', 'rain'],
        ['電', 'でん', 'いかずち', 'electricity / electric powered'],
        ['車', 'しゃ', 'くるま', 'wheel / vehicle / car'],
        ['語', 'ご', 'かたり / かた－る', 'word / speech / language / narration / to tell / to speak'],
        ['耳', '', '', 'ear'],
        ['手', '', '', 'hand'],
        ['足', '', '', 'foot'],
        ['目', '', '', 'eye'],
        ['口', '', '', 'mouth'],
        ['名', 'めい / みょう', 'な', 'name / fame / famous / name'],

        // Places and directions
        ['店', '', '', 'shop'],
        ['駅', '', '', 'station'],
        ['道', '', '', 'street'],
        ['社', '', '', 'shrine / society'],
        ['国', 'こく / ごく', 'くに', 'country / nation'],
        ['外', 'がい / げ / うい', 'ほか / そと', 'outside / foreign / other'],
        ['学', 'がく', 'まな－ぶ', 'school / learning / science / to learn'],
        ['校', 'こう', 'あぜ', 'school'],
        ['上', 'じょう / しょう', 'うえ / うわ / あ－げる / あ－がる / のぼ－る / のぼ－せる / かみ', 'top / above / to raise / to rise / up'],
        ['下', 'か / げ', 'した / しも / さ－げる / さ－がる / くだ－る / くだ－す / お－りる / お－ろす', 'bottom / under / down'],
        ['中', 'ちゅう / じゅう', 'なか / あた－る', 'middle / center / within / inside'],
        ['北', 'ほく', 'きた', 'north'],
        ['西', 'せい / さい', 'にし', 'west'],
        ['東', 'とう', 'ひがし / ひんがし', 'east'],
        ['南', 'なん', 'みなみ', 'south'],
        ['右', 'ゆう / う', 'みぎ', 'right'],
        ['左', 'さ', 'ひだり', 'left'],

        // Verbs
        ['見', 'けん', 'み－る / み－せる', 'to see / to show'],
        ['聞', 'ぶん / もん', 'き－く', 'to hear / to listen / to ask'],
        ['書', 'しょ', 'か－く', 'book / document / to write'],
        ['読', 'どく / とう', 'よ－む', 'to read'],
        ['話', 'わ', 'はなし / はな－す', 'to talk / conversation / topic'],
        ['買', '', '', 'to buy'],
        ['行', 'ぎょう / こう / あん', 'い－く / ゆ－く', 'to go'],
        ['出', 'しゅつ / すい', 'だ－す / いだ－す / で－る', 'to go out / leave'],
        ['入', 'にゅう / じゅ', 'い－る / はい－る', 'enter / to go in / to insert'],
        ['休', 'きゅう', 'やす－み / やす－む', 'to rest / vacation'],
        ['食', 'じき / しょく', 'く－う / た－べる', 'to eat / meal / food'],
        ['飲', '', '', 'to drink'],
        ['言', '', '', 'to talk / word'],
        ['立', '', '', 'to stand'],
        ['会', 'かい / え', 'あ－う', 'to meet / society'],

        // Adjectives
        ['多', '', '', 'a lot / many'],
        ['少', '', '', 'a little / few'],
        ['古', '', '', 'old'],
        ['新', '', '', 'new'],
        ['大', 'だい / たい', 'おお－きい', 'great / big'],
        ['小', 'しょう', 'こ / お / ちい－さい', 'small / little'],
        ['安', '', '', 'cheap / safety / peace'],
        ['高', 'こう', 'たか－い / たか', 'high / costly / tall'],
        ['長', 'ちょう', 'なが－い', 'leader / long'],
        ['白', 'はく / びゃく', 'しろ / しら / しろ－い', 'white']
    ],
    vocabulary: [
        ['一人', 'one person, alone'],
        ['二人', 'two people, pair'],
        ['三日', '3rd day of the month'],
        ['四日', '4th day of the month'],
        ['五日', '5th day of the month'],
        ['六日', '6th day of the month'],
        ['七日', '7th day of the month'],
        ['八日', '8th day of the month'],
        ['九日', '9th day of the month'],
        ['十日', '10th day of the month'],
        ['百万円', '1 million Yen'],
        ['千万円', '10 million Yen'],
        ['万年筆', 'fountain pen'],
        ['円い', 'round'],
        ['明日', 'tomorrow'],
        ['毎週', 'every week'],
        ['月曜日', 'Monday'],
        ['今年', 'this year'],
        ['去年', 'last year'],
        ['時計', 'clock, watch'],
        ['時間', 'time, hours'],
        ['三十分', 'thirty minutes'],
        ['自分', 'oneself'],
        ['午前', 'morning, A.M.'],
        ['名前', 'name'],
        ['午後', 'afternoon, P.M.'],
        ['今晩', 'this evening'],
        ['今朝', 'this morning'],
        ['先週', 'last week'],
        ['先生', 'teacher, master'],
        ['来月', 'next month'],
        ['来る', 'to come'],
        ['半分', 'half'],
        ['毎日', 'every day'],
        ['何曜日', 'what day of the week'],
        ['人々', 'people'],
        ['男の子', 'boy'],
        ['女の子', 'girl'],
        ['子供', 'child'],
        ['母', 'mother'],
        ['父', 'father'],
        ['友達', 'friend'],
        ['火曜日', 'Tuesday'],
        ['水曜日', 'Wednesday'],
        ['木曜日', 'Thursday'],
        ['土曜日', 'Saturday'],
        ['金曜日', 'Friday'],
        ['日本語', 'Japanese'],
        ['川', 'river'],
        ['花火', 'fireworks'],
        ['元気', 'healthy, spirit, fine'],
        ['生徒', 'pupil'],
        ['魚', 'fish'],
        ['天気', 'weather'],
        ['空', 'sky'],
        ['山', 'mountain'],
        ['雨', 'rain'],
        ['電気', 'electricity'],
        ['電車', 'electric train'],
        ['英語', 'English'],
        ['耳', 'ear'],
        ['手紙', 'letter'],
        ['足', 'foot'],
        ['目', 'eye'],
        ['出口', 'exit'],
        ['名前', 'name'],
        ['喫茶店', 'coffee shop'],
        ['駅前', 'in front of the station'],
        ['道具', 'tool'],
        ['社長', 'president of a company'],
        ['外国人', 'foreigner'],
        ['外国', 'foreign country'],
        ['大学', 'university'],
        ['学校', 'school'],
        ['上着', 'jacket'],
        ['靴下', 'socks'],
        ['日中', 'during the day, midday'],
        ['北', 'north'],
        ['西', 'west'],
        ['東京', 'Tokyo'],
        ['南', 'south'],
        ['右', 'right'],
        ['左', 'left'],
        ['見せる', 'to show'],
        ['聞く', 'to listen, to hear'],
        ['辞書', 'dictionary'],
        ['読む', 'to read'],
        ['電話', 'telephone'],
        ['買い物', 'shopping'],
        ['銀行', 'bank'],
        ['出かける', 'to go out'],
        ['入口', 'entrance'],
        ['休む', 'to take a day off'],
        ['食堂', 'dining room'],
        ['飲み物', 'beverage'],
        ['言う', 'to say'],
        ['立つ', 'to stand'],
        ['会社', 'company'],
        ['多い', 'many'],
        ['多分', 'probably'],
        ['少ない', 'few'],
        ['古い', 'old'],
        ['新しい', 'new'],
        ['新聞', 'newspaper'],
        ['大きい', 'big'],
        ['大変', 'dreadful, immense'],
        ['小さい', 'little'],
        ['安い', 'cheap'],
        ['高い', 'expensive'],
        ['長い', 'long'],
        ['部長', 'manager'],
        ['白い', 'white'],
        ['面白い', 'interesting']
    ]
}